export const queryKeys = Object.freeze({
  USER: 'USER',
  ORDER: 'ORDER',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PROFILE: 'PROFILE',
  PRODUCT: 'PRODUCT',
  ONGOING_ORDER_LIST: 'PRODUCT_LIST',
  PRE_ENROLL_ORDER_LIST: 'PRODUCT_LIST',
  MY_AUCTION: 'MY_AUCTION',
  BEST_PRODUCTS: 'BEST_PRODUCTS',
  DEADLINE_PRODUCTS: 'DEADLINE_PRODUCTS',
  PRE_ENROLL_PRODUCTS: 'PRE_ENROLL_PRODUCTS',
  DETAILS: 'DETAILS',
});
