export const queryKeys = Object.freeze({
  USER: 'USER',
  ORDER: 'ORDER',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PROFILE: 'PROFILE',
  PRODUCT: 'PRODUCT',
  NICKNAME: 'NICKNAME',
  AUCTION: 'AUCTION',
  BEST_AUCTIONS: 'BEST_AUCTIONS',
  IMMINENT_AUCTIONS: 'IMMINENT_AUCTIONS',
  PRE_AUCTIONS: 'PRE_AUCTIONS',

  AUCTION_LIST: 'AUCTION_LIST',
  PRE_AUCTION_LIST: 'PRE_AUCTION_LIST',

  USER_AUCTION_REGISTERED: 'USER_AUCTION_REGISTERED',
  USER_PRE_AUCTION_REGISTERED: 'USER_PRE_AUCTION_REGISTERED',

  AUCTION_HISTORY: 'AUCTION_HISTORY',
  AUCTION_WON: 'AUCTION_WON',
  AUCTION_LOST: 'AUCTION_LOST',

  AUCTION_DETAILS: 'DETAILS',
  PRE_AUCTION_DETAILS: 'PRE_AUCTION_DETAILS',
  PRE_AUCTION_HEART_LIST: 'PRE_AUCTION_HEART_LIST',

  NOTIFICATIONS: 'NOTIFICATIONS',
  BIDDER_LIST: 'BIDDER_LIST',
});
