name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main
    # 수동 실행
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

       # 2. Node.js 설치 및 글로벌 npm 캐시 활성화
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # ~/.npm 캐싱
  
      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 기존 빌드 파일 삭제
      - name: Clean build directory
        run: |
          rm -rf dist

      # 5. 빌드 실행
      - name: Build project
        run: npm run build

      # 6. AWS 크레덴셜 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7. S3로 배포
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete --exact-timestamps
          echo "Deployment to S3 and CloudFront completed successfully!"

      # 8. CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          echo "CloudFront Cache Invalidated!"